// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArIo54L_CV5sgp4f0b7xdXovG5Dokm4-A',
    appId: '1:696835799485:web:93ee672ef8280935087ad4',
    messagingSenderId: '696835799485',
    projectId: 'g9-expense-tracker',
    authDomain: 'g9-expense-tracker.firebaseapp.com',
    storageBucket: 'g9-expense-tracker.firebasestorage.app',
    measurementId: 'G-E26PDBHP7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsE7kpzgQoJPtI6h6y8_xWqSKPSz22NNw',
    appId: '1:696835799485:android:e5f0065c801bfb24087ad4',
    messagingSenderId: '696835799485',
    projectId: 'g9-expense-tracker',
    storageBucket: 'g9-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWluo3rivkqteZscm7T5qy1TJunDNEMJs',
    appId: '1:696835799485:ios:556239c81c74b184087ad4',
    messagingSenderId: '696835799485',
    projectId: 'g9-expense-tracker',
    storageBucket: 'g9-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.g9ExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWluo3rivkqteZscm7T5qy1TJunDNEMJs',
    appId: '1:696835799485:ios:556239c81c74b184087ad4',
    messagingSenderId: '696835799485',
    projectId: 'g9-expense-tracker',
    storageBucket: 'g9-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.g9ExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArIo54L_CV5sgp4f0b7xdXovG5Dokm4-A',
    appId: '1:696835799485:web:709e6ffd7eacbc56087ad4',
    messagingSenderId: '696835799485',
    projectId: 'g9-expense-tracker',
    authDomain: 'g9-expense-tracker.firebaseapp.com',
    storageBucket: 'g9-expense-tracker.firebasestorage.app',
    measurementId: 'G-KKE9R5TVDB',
  );

}