// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMVGG8zrBiGjxzS0uD1DHer7Q5XO4xhPE',
    appId: '1:1099396612955:web:82f9cd4c07fbc8fc6f107e',
    messagingSenderId: '1099396612955',
    projectId: 'expense-tracker-th5-20260315',
    authDomain: 'expense-tracker-th5-20260315.firebaseapp.com',
    storageBucket: 'expense-tracker-th5-20260315.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM50tASQCh0pDwtjbNK1uO4qRUlLkzFHA',
    appId: '1:1099396612955:android:4704b7367deba48d6f107e',
    messagingSenderId: '1099396612955',
    projectId: 'expense-tracker-th5-20260315',
    storageBucket: 'expense-tracker-th5-20260315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDseJjZs7vkGyIcZY59jVdm4lm-VHAEKBM',
    appId: '1:1099396612955:ios:99a12ce76c99b0976f107e',
    messagingSenderId: '1099396612955',
    projectId: 'expense-tracker-th5-20260315',
    storageBucket: 'expense-tracker-th5-20260315.firebasestorage.app',
<<<<<<< HEAD
<<<<<<< HEAD
    iosClientId:
        '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
=======
    iosClientId: '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
>>>>>>> origin/feature/categories
=======
    iosClientId:
        '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
>>>>>>> origin/feature/dashboard
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDseJjZs7vkGyIcZY59jVdm4lm-VHAEKBM',
    appId: '1:1099396612955:ios:99a12ce76c99b0976f107e',
    messagingSenderId: '1099396612955',
    projectId: 'expense-tracker-th5-20260315',
    storageBucket: 'expense-tracker-th5-20260315.firebasestorage.app',
<<<<<<< HEAD
<<<<<<< HEAD
    iosClientId:
        '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
=======
    iosClientId: '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
>>>>>>> origin/feature/categories
=======
    iosClientId:
        '1099396612955-k11rdeisbst7jjmf1bk19vbtk4rmj9od.apps.googleusercontent.com',
>>>>>>> origin/feature/dashboard
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMVGG8zrBiGjxzS0uD1DHer7Q5XO4xhPE',
    appId: '1:1099396612955:web:946998d31af92bd86f107e',
    messagingSenderId: '1099396612955',
    projectId: 'expense-tracker-th5-20260315',
    authDomain: 'expense-tracker-th5-20260315.firebaseapp.com',
    storageBucket: 'expense-tracker-th5-20260315.firebasestorage.app',
  );
<<<<<<< HEAD
<<<<<<< HEAD
}
=======

}
>>>>>>> origin/feature/categories
=======
}
>>>>>>> origin/feature/dashboard
